### ISSUE TITLE
javascript running error code ; TypeError: Cannot read property 'click' of null

### ISSUE THREAD

**Issue by Malatya-Uyducu** [LJeremy/instaccept#1]
I am loginned and chrome console  code copy runinng .

Uncaught TypeError: Cannot read property 'click' of null
    at <anonymous>:8:116
(anonymous) @ VM219:8
setTimeout (async)
(anonymous) @ VM219:7
setTimeout (async)
(anonymous) @ VM219:5
![1s](https://user-images.githubusercontent.com/39598877/40551577-0c81b432-6046-11e8-953a-95d8f495a49a.jpg)
![2s](https://user-images.githubusercontent.com/39598877/40551578-0cb28ea4-6046-11e8-8ea9-346aa0fbdbd4.jpg)

[https://preview.ibb.co/nE2t6T/1s.jpg](https://preview.ibb.co/nE2t6T/1s.jpg)

[https://preview.ibb.co/ftSh0o/2s.jpg](https://preview.ibb.co/ftSh0o/2s.jpg)

**Comment by LJeremy** [comment]
I am unable to recreate the problem, but it appears the second XPath is invalid. This is how you can fix it: 

When in Developers tool, select the first list item in the list (Followers button). Select the XPath of that element. Right Click -> Copy -> XPath. Change the second XPath to the one you just copied. 

This should fix the bug.
