### ISSUE TITLE
Chrome extension is outdated

### ISSUE THREAD

**Issue by LJeremy** [LJeremy/instaccept#13]
Chrome extension file (.crx) is outdated. Fix this by following the instructions in the README.

**Comment by ShubhamSood1406** [comment]
Can I work on it, please assign it to me.

**Comment by LJeremy** [comment]
Yes, go ahead.

**Comment by HellBender2011** [comment]
it asks for .pem file - 'Pack extension error
A private key for specified extension already exists.'
please provide .pem file or guide me.
