### ISSUE TITLE
Make README more fun.

### ISSUE THREAD

**Issue by LJeremy** [LJeremy/instaccept#2]
Add some Emoji's or even change the styling. All up to you!

**Comment by bhagatparwinder** [comment]
I can do it

**Comment by LJeremy** [comment]
Go for it!

**Comment by bhagatparwinder** [comment]
@LJeremy Added a PR. A lot more could be done as the project expands but this should be cleaner.

**Comment by LJeremy** [comment]
Thanks, merged.
