### ISSUE TITLE
Instagram limitations

### ISSUE THREAD

**Issue by andreich1980** [LJeremy/instaccept#7]
Isn't it dangerous to click 100 "accept" buttons at once? What is the recommended delay between clicks?
The script imitates a real user, so I guess maybe 3 clicks a second would be fine. What do you think?

**Comment by justnew11** [comment]
Try to add a 4 second delay between Accepting and accept randomly

**Comment by andreich1980** [comment]
@justnew11 nice idea, thank you.

**Comment by justnew11** [comment]
Have you tried the script is this working fine for you did you face any other issues while running this script?

**Comment by LJeremy** [comment]
Closed, fixed by #11
